//
//  File.swift
//  Noms
//
//  Created by Annie Chu on 5/1/15.
//  Copyright (c) 2015 COS333. All rights reserved.
//

import UIKit

class List: NSObject {
    class func names() -> Array <String> {
        return [
            "Bagels",
            "Bakeries",
            "Beer, Wine & Spirits",
            "Beverage Store",
            "Breweries",
            "Bubble Tea",
            "Butcher",
            "CSA",
            "Churros",
            "Coffee & Tea",
            "Coffee & Tea Supplies",
            "Convenience Stores",
            "Cupcakes",
            "Delicatessen",
            "Desserts",
            "Distilleries",
            "Do-It-Yourself Food",
            "Donairs",
            "Doughnuts",
            "Ethic Grocery",
            "Ethnic Grocery",
            "Farmers' Market",
            "Fishmonger",
            "Food Delivery Services",
            "Food Trucks",
            "Friterie",
            "Gelato",
            "Grocery",
            "Hawker Centre",
            "Honey",
            "Ice Cream & Frozen Yogurt",
            "Internet Cafes",
            "Japanese Sweets",
            "Juice Bars & Smoothies",
            "Kiosk",
            "Milkshake Bars",
            "Mulled Wine",
            "Organic Stores",
            "Panzerotti",
            "Parent Cafes",
            "Patisserie/Cake Shop",
            "Piadina",
            "Pretzels",
            "Salumerie",
            "Shaved Ice",
            "Specialty Food",
            "Candy Stores",
            "Cheese Shops",
            "Chocolatiers & Shops",
            "Ethnic Food",
            "Fruits & Veggies",
            "Health Food Store",
            "Herbs & Spices",
            "Meat Shops",
            "Pasta Shops",
            "Seafood Markets",
            "Tofu Shops",
            "Street Vendors",
            "Tea Rooms",
            "Wineries",
            "Zapiekanka",
            "Restaurants",
            "Afghan",
            "African",
            "Senegalese",
            "South African",
            "American",
            "American",
            "Arabian",
            "Arab Pizza",
            "Argentine",
            "Armenian",
            "Asian Fusion",
            "Asturian",
            "Australian",
            "Austrian",
            "Baguettes",
            "Bangladeshi",
            "Barbeque",
            "Basque",
            "Bavarian",
            "Beer Garden",
            "Beer Hall",
            "Beisl",
            "Belgian",
            "Flemish",
            "Bistros",
            "Black Sea",
            "Brasseries",
            "Brazilian",
            "Brazilian Empanadas",
            "Central Brazilian",
            "Northeastern Brazilian",
            "Northern Brazilian",
            "Rodizios",
            "Breakfast & Brunch",
            "British",
            "Buffets",
            "Bulgarian",
            "Burgers",
            "Burmese",
            "Cafes",
            "Cafeteria",
            "Cajun/Creole",
            "Cambodian",
            "Canadian",
            "Canteen",
            "Caribbean",
            "Dominican",
            "Haitian",
            "Puerto Rican",
            "Trinidadian",
            "Catalan",
            "Chech",
            "Cheesesteaks",
            "Chicken Shop",
            "Chicken Wings",
            "Chilean",
            "Chinese",
            "Cantonese",
            "Congee",
            "Dim Sum",
            "Fuzhou",
            "Hakka",
            "Henghwa",
            "Hokkien",
            "Hunan",
            "Pekinese",
            "Shanghainese",
            "Szechuan",
            "Teochew",
            "Comfort Food",
            "Corsican",
            "Creperies",
            "Cuban",
            "Curry Sausage",
            "Cypriot",
            "Czech",
            "Czech/Slovakian",
            "Danish",
            "Delis",
            "Diners",
            "Dumplings",
            "Eastern European",
            "Ethiopian",
            "Fast Food",
            "Filipino",
            "Fischbroetchen",
            "Fish & Chips",
            "Fondue",
            "Food Court",
            "Food Stands",
            "French",
            "Alsatian",
            "Auvergnat",
            "Berrichon",
            "Bourguignon",
            "Nicoise",
            "Provencal",
            "French Southwest",
            "Galician",
            "Gastropubs",
            "Georgian",
            "German",
            "Baden",
            "Eastern German",
            "Hessian",
            "Northern German",
            "Palatine",
            "Rhinelandian",
            "Giblets",
            "Gluten-Free",
            "Greek",
            "Halal",
            "Hawaiian",
            "Heuriger",
            "Himalayan/Nepalese",
            "Hong Kong Style Cafe",
            "Hot Dogs",
            "Hot Pot",
            "Hungarian",
            "Iberian",
            "Indian",
            "Indonesian",
            "International",
            "Irish",
            "Island Pub",
            "Israeli",
            "Italian",
            "Abruzzese",
            "Altoatesine",
            "Apulian",
            "Calabrian",
            "Cucina campana",
            "Emilian",
            "Friulan",
            "Ligurian",
            "Lumbard",
            "Napoletana",
            "Piemonte",
            "Roman",
            "Sardinian",
            "Sicilian",
            "Tuscan",
            "Venetian",
            "Japanese",
            "Blowfish",
            "Conveyor Belt Sushi",
            "Donburi",
            "Gyudon",
            "Oyakodon",
            "Hand Rolls",
            "Horumon",
            "Izakaya",
            "Japanese Curry",
            "Kaiseki",
            "Kushikatsu",
            "Oden",
            "Okinawan",
            "Okonomiyaki",
            "Onigiri",
            "Ramen",
            "Robatayaki",
            "Soba",
            "Sukiyaki",
            "Takoyaki",
            "Tempura",
            "Teppanyaki",
            "Tonkatsu",
            "Udon",
            "Unagi",
            "Western Style Japanese Food",
            "Yakiniku",
            "Yakitori",
            "Jewish",
            "Kebab",
            "Korean",
            "Kosher",
            "Kurdish",
            "Laos",
            "Laotian",
            "Latin American",
            "Colombian",
            "Salvadoran",
            "Venezuelan",
            "Live/Raw Food",
            "Lyonnais",
            "Malaysian",
            "Mamak",
            "Nyonya",
            "Meatballs",
            "Mediterranean",
            "Falafel",
            "Mexican",
            "Eastern Mexican",
            "Jaliscan",
            "Northern Mexican",
            "Oaxacan",
            "Pueblan",
            "Tacos",
            "Tamales",
            "Yucatan",
            "Middle Eastern",
            "Egyptian",
            "Lebanese",
            "Milk Bars",
            "Modern Australian",
            "Modern European",
            "Mongolian",
            "Moroccan",
            "New Zealand",
            "Night Food",
            "Norcinerie",
            "Open Sandwiches",
            "Oriental",
            "Pakistani",
            "Parent Cafes",
            "Parma",
            "Persian/Iranian",
            "Peruvian",
            "Pita",
            "Pizza",
            "Polish",
            "Pierogis",
            "Portuguese",
            "Alentejo",
            "Algarve",
            "Azores",
            "Beira",
            "Fado Houses",
            "Madeira",
            "Minho",
            "Ribatejo",
            "Tras-os-Montes",
            "Potatoes",
            "Poutineries",
            "Pub Food",
            "Rice",
            "Romanian",
            "Rotisserie Chicken",
            "Rumanian",
            "Russian",
            "Salad",
            "Sandwiches",
            "Scandinavian",
            "Scottish",
            "Seafood",
            "Serbo Croatian",
            "Signature Cuisine",
            "Singaporean",
            "Slovakian",
            "Soul Food",
            "Soup",
            "Southern",
            "Spanish",
            "Arroceria / Paella",
            "Sri Lankan",
            "Steakhouses",
            "Sushi Bars",
            "Swabian",
            "Swedish",
            "Swiss Food",
            "Tabernas",
            "Taiwanese",
            "Tapas Bars",
            "Tapas/Small Plates",
            "Tex-Mex",
            "Thai",
            "Traditional Norwegian",
            "Traditional Swedish",
            "Trattorie",
            "Turkish",
            "Chee Kufta",
            "Gozleme",
            "Turkish Ravioli",
            "Ukrainian",
            "Uzbek",
            "Vegan",
            "Vegetarian",
            "Venison",
            "Vietnamese",
            "Wok",
            "Wraps",
            "Yugoslav"
]
    }
}
